version: 2
jobs:
   build:
     docker:
        - image: deangiberson/aws-dynamodb-local
     steps:
        - checkout
        - run:
           name: install java
           command: |
              apt-get update && apt-get install default-jre default-jdk
        - run:
          name: accept java
          command: | 
            y
        - run:
           name: setup container
           command: |
              curl -k -L -o dynamodb-local.tgz http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
              tar -xzf dynamodb-local.tgz
              java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb
